export const q = {
  latestPosts: (categorySlug?: string) => {
    const catFilter = categorySlug ? `&& category->slug.current == "${categorySlug}"` : ''
    return `*[_type=="post" ${catFilter}]|order(publishedAt desc)[0...30]{
      _id,
      title,
      slug,
      excerpt,
      publishedAt,
      category->{title, slug},
      heroImage{
        asset->{
          _id,
          url,
          metadata{
            dimensions
          }
        }
      },
      readTime
    }`
  },
  postBySlug: `*[_type=="post" && slug.current == $slug][0]{
    _id,
    title,
    slug,
    excerpt,
    publishedAt,
    category->{title, slug},
    heroImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    body[]{
      ...,
      _type == "image" => {
        ...,
        asset->{
          _id,
          url,
          metadata{
            dimensions
          }
        }
      }
    },
    readTime
  }`,
  listingsByType: `*[_type=="listing" && listingType == $type]|order(featured desc, name asc)[0...60]{
    _id,
    name,
    slug,
    listingType,
    city,
    address,
    heroImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    website,
    phone,
    hours,
    amenities,
    featured
  }`,
  listingBySlug: `*[_type=="listing" && slug.current == $slug][0]{
    _id,
    name,
    slug,
    listingType,
    city,
    address,
    heroImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    website,
    phone,
    description,
    hours,
    amenities,
    socials,
    featured
  }`,
  dealsFeatured: `*[_type=="deal" && featured == true]|order(priority desc, startDate desc)[0...12]{
    _id,
    title,
    slug,
    brandName,
    dispensaryName,
    city,
    startDate,
    endDate,
    terms,
    heroImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    link
  }`,
  eventsUpcoming: `*[_type=="event" && dateTime >= now()]|order(dateTime asc)[0...30]{
    _id,
    title,
    slug,
    dateTime,
    venueName,
    city,
    heroImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    link
  }`,
  adByPlacement: (placement: string) => `*[_type=="ad" && placement == $placement && active == true && (!defined(startDate) || startDate <= now()) && (!defined(endDate) || endDate >= now())]|order(priority desc)[0]{
    _id,
    title,
    advertiser,
    placement,
    adType,
    image{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    html,
    headline,
    cta,
    url,
    priority
  }`,
  activeRadioStations: `*[_type=="radioStation" && active == true]|order(order asc){
    _id,
    title,
    streamUrl,
    active,
    order,
    coverImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions
        }
      }
    },
    genre
  }`
}
